### ISSUE TITLE
Add bullets and arrows in Counter option

### ISSUE THREAD

**Issue by GGustavoGuerra** [shazahm1/Easy-Table-of-Contents#80]
Besides the numerical versions already present, I think it would be interesting to put 2 visual options, such as bullet or arrows lists.

![options](https://user-images.githubusercontent.com/12565511/65713376-70cd3880-e06f-11e9-9790-2024f16e174b.png)
![bullets](https://user-images.githubusercontent.com/12565511/65713383-7460bf80-e06f-11e9-9b9b-bce8bd6aae04.png)
![arrows](https://user-images.githubusercontent.com/12565511/65713380-7296fc00-e06f-11e9-9a40-eb3a946b374c.png)

**Comment by vburlak** [comment]
+1 I've got the same issue.
No built-in way to customize this feature using filters or something like that

**Comment by shazahm1** [comment]
Note to self: this CSS seems to work great for bullets:

``` css
.ez-toc-widget-container ul.ez-toc-list .ez-toc-list-level-4 a {
  display: flex;
}
.ez-toc-widget-container ul.ez-toc-list .ez-toc-list-level-4 a::before {
  border-radius: 50%;
  content: "";
  line-height: 1em;
  margin: .5em 6px 0 0;
  height: .5em;
  width: .5em;
  position: relative;
	background-color: #666666;
  min-width: .5em;
}
```

**Comment by shazahm1** [comment]
Note to self: this CSS seems to work great for arrows:

``` css
.ez-toc-widget-container ul.ez-toc-list .ez-toc-list-level-4 a::before { 
    content: "";
    border-color: transparent #666666;
    border-style: solid;
    border-width: 0.35em 0 0.35em 0.45em;
    border-radius: 0;
    display: block;
    height: 0;
    width: 0;
    min-width: .45em;
    margin: .35em 0;
}
```
